package main

import (
	"errors"
	"fmt"
	"strconv"
	"strings"
)

type ConfigSpec []*GenConfigItem

type GenConfigItem struct {
	Key     string
	IsList  bool
	Default string
	Comment []string
}

type Config struct {
	Default any
	ValType int
	Value   any
}

type ConfigRegistry map[string]*Config

func ValidateConfig(magicLine string) error {
	if !strings.HasPrefix(magicLine, "Generated with rshred") {
		return fmt.Errorf("unable to detect config file version.\nthis can be caused by the config file being generated by an rshred version older than v3.0.0, or the first line of the file being corrupted.")
	} else if confVersion := strings.TrimSpace(strings.TrimPrefix(magicLine, "Generated with rshred ")); confVersion != rVersion {
		return fmt.Errorf("version of config file (%v) differs from version of rshred (%v)", confVersion, rVersion)
	} else {
		return nil
	}
}

func GenConfig(spec ConfigSpec) []string {
	fileCap := 0
	for _, item := range spec {
		fileCap = fileCap + 2
		if comNum := len(item.Comment); comNum > 0 {
			fileCap = fileCap + comNum + 1
		}
		if item.IsList {
			fileCap = fileCap + 2
		}
	}
	confOut := make([]string, fileCap)
	line := 0
	for _, item := range spec {
		if !item.IsList {
			for i, comment := range item.Comment {
				confOut[line+i] = fmt.Sprintf("# %v", comment)
			}
			if comNum := len(item.Comment); comNum > 0 {
				line = line + comNum + 1
			}
			confOut[line] = fmt.Sprintf("%v=%v", item.Key, item.Default)
			line = line + 2
		} else {
			for i, comment := range item.Comment {
				confOut[line+i] = fmt.Sprintf("# %v", comment)
			}
			if comNum := len(item.Comment); comNum > 0 {
				line = line + comNum + 1
			}
			confOut[line] = fmt.Sprintf("%v= {", item.Key)
			confOut[line+2] = "}"
			line = line + 4
		}
	}
	return confOut
}

func LoadDefault(registry ConfigRegistry) {
	for _, conf := range registry {
		if conf.ValType == 0 {
			switch conf.Default {
			case "ON":
				conf.Value = true
			case "OFF":
				conf.Value = false
			default:
				panic("config item is bool, but default isn't ON or OFF")
			}
		} else {
			conf.Value = conf.Default
		}
	}
}

func ParseConfig(confFile []string, registry ConfigRegistry) []error {
	var errs []error
	inList := false
	list := []string{}
	listLn := 0
	var listEntry *Config
	for i, line := range confFile {
		if inList {
			if strings.TrimSpace(line) == "}" {
				inList = false
				listEntry.Value = list
				list = []string{}
			} else if strings.TrimSpace(line) != "" {
				list = append(list, line)
			}
		} else {
			if strings.HasPrefix(line, "#") || line == "" {
				continue
			}
			key, value, found := strings.Cut(line, "=")
			if !found {
				errs = append(errs, fmt.Errorf("line %v: does not contain \"=\"", i+1))
				continue
			}
			conf, ok := registry[key]
			if !ok {
				errs = append(errs, fmt.Errorf("line %v: unrecognized key: %q", i+1, key))
			} else {
				switch conf.ValType {
				case 0:
					switch value {
					case "ON":
						conf.Value = true
					case "OFF":
						conf.Value = false
					default:
						errs = append(errs, fmt.Errorf("line %v: value of %q must be either \"ON\" or \"OFF\"", i+1, key))
					}
				case 1:
					num, err := strconv.Atoi(value)
					if err != nil {
						if errors.Is(err, strconv.ErrRange) {
							errs = append(errs, fmt.Errorf("line %v: value of %q too large", i+1, key))
						} else {
							errs = append(errs, fmt.Errorf("line %v: value of %q must be an integer", i+1, key))
						}
					} else {
						conf.Value = num
					}
				case 2:
					conf.Value = value
				case 3:
					listLn = i
					listEntry = conf
					inList = true
				default:
					panic(fmt.Sprintf("invalid conf value %q", conf.ValType))
				}
			}
		}
	}
	if inList {
		errs = append(errs, fmt.Errorf("line %v: list has no closing brace", listLn+1))
	}
	return errs
}
