#!/usr/bin/env bash
trap "caughtsig" INT HUP
# rshred version
rversion="v3.0.0-alpha"
# Set home directory.
if [[ -n $SUDO_USER ]]; then
    homedir="/home/$SUDO_USER"
else
    homedir="$HOME"
fi
# Default script variables.
confpath="$homedir/.config/rshred/"
conffile="$confpath""rshred.conf"
tempexist=0
logsyes=0
shredstarted=0
# Default config variables.
notemp=OFF
checkupdates=OFF
shredtemps=ON
logpath="$homedir/.rshred/logs/"
tmppath="$XDG_RUNTIME_DIR"
yesexclude=ON
exclprompt=OFF
excludedirs=()
rmvdir=ON
stopexcl=END_OF_DIRS
# Helper functions.
shredtemps() {
    if [[ $oldtempexist == 1 ]]; then
        if [[ "$shredtemps" == "ON" ]]; then
            echo ""
            echo "Shredding tempfile at $oldtemp..."
            shred -fuz -n 5 "$oldtemp" > /dev/null 2>&1
            if [[ $? != 0 ]]; then
                echo ""
                echo "WARNING! Shredding of tempfile located at $oldtemp failed!" | tee -a "$logpath"
            fi
        else
            echo ""
            echo "Removing tempfile at $oldtemp..."
            rm -f "$oldtemp" > /dev/null 2>&1
            if [[ $? != 0 ]]; then
                echo ""
                echo "WARNING! Removal of tempfile located at $oldtemp failed!" | tee -a "$logpath"
            fi
        fi
    fi
    if [[ $tempexist == 1 ]]; then
        if [[ "$shredtemps" == "ON" ]]; then
            echo ""
            echo "Shredding tempfile at $crnttemp..."
            shred -fuz -n 5 "$crnttemp" > /dev/null 2>&1
            if [[ $? != 0 ]]; then
                echo ""
                echo "WARNING! Shredding of tempfile located at $crnttemp failed!" | tee -a "$logpath"
            fi
        else
            echo ""
            echo "Removing tempfile at $crnttemp..."
            rm -f "$crnttemp" > /dev/null 2>&1
            if [[ $? != 0 ]]; then
                echo ""
                echo "WARNING! Removal of tempfile located at $crnttemp failed!" | tee -a "$logpath"
            fi
        fi
    fi
}
caughtsig() {
    echo ""
    echo "Caught interrupt signal!"
    if [[ $logsyes == 1 && $shredstarted == 1 ]]; then
        echo ""
        echo "Appending to logfile..."
        echo -e "------------------------\nCaught interrupt at $(date).\n------------------------" >> "$logpath"
        if [[ $? != 0 ]]; then
            echo "WARNING! Appending to logfile failed!"
        fi
    fi
    shredtemps
    echo ""
    echo "Quitting..."
    exit 0
}
createconf() {
    mkdir -p "$confpath"
    echo "Generated with rshred ${rversion}." > "$conffile"
    echo "" >> "$conffile"
    echo "# Checks for updates on boot. (ON/OFF) Default: OFF" >> "$conffile"
    echo "" >> "$conffile"
    echo "CheckForUpdates=${checkupdates}" >> "$conffile"
    echo "" >> "$conffile"
    echo "# Disables creation of temp files alltogether. Will disable functionality for recursive permission checking, error detection, and error counting. (ON/OFF) Default: OFF" >> "$conffile"
    echo "" >> "$conffile"
    echo "NoTemp=${notemp}" >> "$conffile"
    echo "" >> "$conffile"
    echo "# Shred any temporary files after they are done being used. Highly reccomended to disable if temporary files are being written to an SSD. (ON/OFF) Default: ON" >> "$conffile"
    echo "" >> "$conffile"
    echo "ShredTemps=${shredtemps}" >> "$conffile"
    echo "" >> "$conffile"
    echo "# Full path for the logfiles. Default: $homedir/.rshred/logs/" >> "$conffile"
    echo "" >> "$conffile"
    echo "LogPath=${logpath}" >> "$conffile"
    echo "" >> "$conffile"
    echo "# Full path for temp files. Default: '$XDG_RUNTIME_DIR' " >> "$conffile"
    echo "" >> "$conffile"
    echo "TempPath=${tmppath}" >> "$conffile"
    echo "" >> "$conffile"
    echo "# Enables the exclusion of directories set below. (ON/OFF) Default: ON" >> "$conffile"
    echo "" >> "$conffile"
    echo "ExcludeConfigDirs=${yesexclude}" >> "$conffile"
    echo "" >> "$conffile"
    echo "# Displays a prompt after flag selection for directories to exclude from shredding on a per-run basis. (ON/OFF) Default: OFF" >> "$conffile"
    echo "" >> "$conffile"
    echo "ExcludeDirsPrompt=${exclprompt}" >> "$conffile"
    echo "" >> "$conffile"
    echo "# Full paths of directories you always want to exclude from shredding." >> "$conffile"
    echo "# Replace \"END_OF_DIRS\" at the beginning and end of the list with something that is NOT the name of any of the directories you want to exclude." >> "$conffile"
    echo "# Put one directory per line." >> "$conffile"
    echo "# Do not put quotes around directory paths, even if they contain spaces." >> "$conffile"
    echo "" >> "$conffile"
    echo "ExcludedDirectories << ${stopexcl}" >> "$conffile"
    printf '%s\n' "${excludedirs[@]}" >> "$conffile"
    echo "${stopexcl}" >> "$conffile"
    echo "" >> "$conffile"
    echo "# Also attempt to remove all empty directories after shred if the -u flag is used. (ON/OFF) Default: OFF" >> "$conffile"
    echo "" >> "$conffile"
    echo "RemoveDirectories=OFF" >> "$conffile"
    if [[ -n "$SUDO_USER" && $EUID == 0 ]]; then
        chown "$SUDO_USER":"$SUDO_USER" "$conffile"
        chmod 660 "$conffile"
    fi
}
loadconf() {
    notemp=""
    logpath=""
    tmppath=""
    excludedirs=()
    badexclude=()
    stopexcl=""
    collectexcl=0
    alreadysawversion=0
    confloop=1
    while IFS= read -r line || [[ -n "$line" ]]; do
        if [[ $collectexcl == 1 ]]; then
            if [[ "$line" == "$stopexcl" ]]; then
                collectexcl=0
            else
                if [[ -d "$line" ]]; then
                    excludedirs+=("$line")
                    continue
                elif [[ -n "$line" ]]; then
                    badexclude+=("$line")
                    continue
                else
                    continue
                fi
            fi
        fi
        if [[ "$line" =~ ^# ]] || [[ -z "$line" ]] || [[ "$line" =~ ^Generated[[:space:]]with[[:space:]]rshred[[:space:]](.*)\.$ ]]; then
            continue
        fi
        if [[ "$line" =~ ^([^=]+)=(.*)$ ]]; then
            key="${BASH_REMATCH[1]}"
            value="${BASH_REMATCH[2]}"
            case "$key" in
                NoTemp)
                       notemp="$value"
                      ;;
                LogPath)
                        logpath="$(realpath "$value")"
                      ;;
                TempPath)
                        tmppath="$(realpath "$value")"
                      ;;
                ExcludeConfigDirs)
                              yesexclude="$value"
                      ;;
                ExcludeDirsPrompt)
                              exclprompt="$value"
                      ;;
                RemoveDirectories)
                                  rmvdir="$value"
                      ;;
                CheckForUpdates)
                                checkupdates="$value"
                      ;;
                ShredTemps)
                           shredtemps="$value"
                      ;;
            esac
        fi
        if [[ "$line" =~ ^ExcludedDirectories[[:space:]]*\<\<[[:space:]]*(.*)$ ]]; then
            collectexcl=1
            stopexcl="${BASH_REMATCH[1]}"
            continue
        fi
    done < "$conffile"
}
# True start. First possibility of an echo statement visible to the user in the terminal.
if [[ $EUID == 0 ]]; then
    echo "WARNING! This script is being run as ROOT! This can be incredibly dangerous if you don't know what you're doing!"
    echo ""
    echo "Type \"YES\" to confirm you understand the risks."
    read rootconfirm
    if [[ "$rootconfirm" != "YES" ]]; then
        echo ""
        echo "Script aborted."
        exit 55
    else
        echo ""
    fi
fi
if [[ ! -f "$conffile" ]]; then
    echo "$homedir/.config/rshred/rshred.conf does not exist. Would you like to create it? (Y/n)"
    read confcreate
    if [[ ! "$confcreate" == n && ! "$confcreate" == N ]]; then
        createconf
    else
        echo ""
        echo "rshred will use default settings until a configuration file is generated."
    fi
else
    IFS= read -r confversionline < "$conffile"
    if [[ "$confversionline" =~ ^Generated[[:space:]]with[[:space:]]rshred[[:space:]](.*)\.$ ]]; then
        confversion="${BASH_REMATCH[1]}"
        if [[ $confversion != $rversion ]]; then
            echo "Configuration file version (${confversion}) does not match rshred version (${rversion}). Would you like to regenerate your config file? Your current settings will be preserved where possible. (Y/n)"
            read -r fixconf
            if [[ "$fixconf" != "N" && "$fixconf" != "n" ]]; then
                loadconf
                createconf
            else
                echo ""
                echo "rshred will use default settings until a new configuration file is generated."
            fi
        else
            loadconf
        fi
    else
        echo ""
        echo "Unable to verify configuration file version."
        echo "This could be due to the configuration file being generated by a version of rshred older than v3.0.0, or the first line of the file being modified."
        echo "Would you like to regenerate your config file? Your current settings will be preserved where possible. (Y/n)"
        read -r fixconf
        if [[ "$fixconf" != "N" && "$fixconf" != "n" ]]; then
            loadconf
            createconf
        else
            echo ""
            echo "rshred will use default settings until a new configuration file is generated."
        fi
    fi
fi
echo ""
echo "rshred Copyright 2025 TrollgeEngineering"
echo ""
echo -e "This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation,\neither version 3 of the License, or (at your option) any later version."
echo ""
echo -e "This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.\nSee the GNU General Public License for more details."
echo ""
echo "You should have received a copy of the GNU General Public License along with this program. If not, see <https://www.gnu.org/licenses/>."
if [[ "$notemp" == "OFF" ]]; then
    if [[ "$tmppath" != "$XDG_RUNTIME_DIR" ]]; then
        if [[ ! -w "$tmppath" || ! -x "$tmppath" ]]; then
            echo ""
            echo -e "\e[31;40mWARNING: Custom temp directory $tmppath is unable to be written to!\nPlease check $conffile to make sure tmppath is correct and has both write and execute permissions.\e[0m"
            echo ""
            echo -e "\e[31;40mFalling back to $XDG_RUNTIME_DIR.\e[0m"
            if [[ ! -w "$XDG_RUNTIME_DIR" || ! -x "$XDG_RUNTIME_DIR" ]]; then
                echo ""
                echo -e "\e[31;40mWARNING: '$XDG_RUNTIME_DIR' is unable to be written to!\e[0m"
                echo ""
                echo -e "\e[31;40mFalling back to /tmp! /tmp is sometimes NOT ram-backed!\e[0m"
                if [[ ! -w /tmp || ! -x /tmp ]]; then
                    echo ""
                    echo -e "\e[31;40mWARNING: /tmp is unable to be written to! Temporary files will be disabled along with some functionality!\e[0m"
                    notemp=ON
                else
                    tmppath=/tmp
                fi
            else
                tmppath="$XDG_RUNTIME_DIR"
            fi
        fi
    else
        if [[ ! -w "$XDG_RUNTIME_DIR" || ! -x "$XDG_RUNTIME_DIR" ]]; then
            echo ""
            echo -e "\e[31;40mWARNING: $XDG_RUNTIME_DIR is unable to be written to!\e[0m"
            echo ""
            echo -e "\e[31;40mFalling back to /tmp.\e[0m"
            if [[ ! -w /tmp || ! -x /tmp ]]; then
                echo ""
                echo -e "\e[31;40mWARNING: /tmp is unable to be written to! Temporary files will be disabled along with some functionality!\e[0m"
                notemp=ON
            else
                tmppath=/tmp
            fi
        fi
    fi
fi

if [[ "$notemp" == OFF ]]; then
    echo ""
    echo -e "\e[33;40mNOTE: Tempfiles containing filepaths will be written to $(realpath $tmppath). This can be disabled in $conffile.\e[0m"
    echo ""
fi
if [[ "${#badexclude[@]}" != 0 ]]; then
    echo -e "\e[31;40mWARNING: The following directory paths from $conffile are invalid, and are unable to be excluded:\e[0m"
    echo ""
    printf '%s\n' "${badexclude[@]}"
    echo ""
fi
if [[ -e $conffile ]]; then
    echo ""
    echo "Configuration file located at $conffile."
    echo ""
fi
if [[ "$checkupdates" == "ON" ]]; then
    if command -v curl > /dev/null 2>&1; then
        echo ""
        echo "Checking for updates..."
        echo ""
        lateststable="$(curl -fsSL https://codeberg.org/TrollgeEngineering/rshred/raw/branch/main/version.txt 2>/dev/null )"
        if [[ $? != 0 ]]; then
            echo "ERROR: Unable to retrive latest version number from server."
        elif [[ $rversion != $lateststable ]]; then
            echo -e "\e[0;32mVersion $lateststable of rshred is available! Get it at https://codeberg.org/TrollgeEngineering/rshred.\e[0m"
        else
            echo "rshred is up to date."
        fi
    elif command -v wget > /dev/null 2>&1; then
        lateststable="$(wget -qO- https://codeberg.org/TrollgeEngineering/rshred/raw/branch/main/version.txt > /dev/null 2>&1 )"
        if [[ $? != 0 ]]; then
            echo "ERROR: Unable to retrive latest version number from server."
        elif [[ $rversion != $lateststable ]]; then
            echo -e "\e[0;32mVersion $lateststable of rshred is available! Get it at https://codeberg.org/TrollgeEngineering/rshred.\e[0m"
        else
            echo "rshred is up to date."
        fi
    else
        echo "ERROR: Either curl or wget is needed for checking updates."
    fi
    echo ""
fi
echo "Welcome to rshred $rversion! Please enter the file/directory you would like to shred."
IFS= read -r shredvictim
if [ ! -e "$shredvictim" ]; then
    echo ""
    echo "error: The directory/file \"$shredvictim\" does not exist. Please check to make sure the file exists and/or you have the right path."
    exit 1
fi
# If the target is a directory, the user is required to have read permissions to list its contents, and execute permissions to traverse it.
if [[ -d "$shredvictim" && ( ! -r "$shredvictim" || ! -x "$shredvictim" ) ]]; then
    echo ""
    echo "error: You do not have read and/or execute permissions on the directory $(realpath "$shredvictim"). Using sudo rshred may help. Use with extreme caution."
    exit 2
# Shred only requires write permissions to shred files.
elif [[ ! -d "$shredvictim" && ! -w "$shredvictim" ]]; then
    echo "error: You do not have write permissions on $shredvictim. Using sudo rshred may help. Use with extreme caution."
    exit 3
fi
shredvictim="$(realpath "$shredvictim")"
# If the user has specified a directory to be shredded, and they have the right permissions on the directory, then their permissions on the files and directories within must also be correct.
if [[ -d "$shredvictim" && "$notemp" == OFF ]]; then
    echo ""
    echo "Scanning for files without write permissions in $shredvictim..."
    if find "$shredvictim" -type f '!' -writable -print -quit 2>/dev/null | grep -q .; then
        anybadfile=1
        tempexist=1
        crnttemp="$(mktemp -p "$tmppath")"
        echo "" >> "$crnttemp"
        echo "FILES WITHOUT WRITE PERMISSIONS" >> "$crnttemp"
        echo "---------------------------------" >> "$crnttemp"
        find "$shredvictim" -type f '!' -writable 2>/dev/null 1>>"$crnttemp"
        echo "-----------------------------------" >> "$crnttemp"
    fi
    echo "Scanning for directories without read/execute permissions in $shredvictim..."
    if find "$shredvictim" -type d \( '!' -readable -o '!' -executable \) -print -quit 2>/dev/null | grep -q .; then
        if [[ $tempexist != 1 ]]; then
            tempexist=1
            crnttemp="$(mktemp -p "$tmppath")"
        fi
        anybaddirec=1
        echo "" >> "$crnttemp"
        echo "DIRECTORIES WITHOUT READ/EXECUTE PERMISSIONS" >> "$crnttemp"
        echo "---------------------------------------------" >> "$crnttemp"
        find "$shredvictim" -type d \( '!' -readable -o '!' -executable \) 2>/dev/null 1>>"$crnttemp"
    fi
    if [[ $anybaddirec == "1" || $anybadfile == "1" ]]; then
        cat "$crnttemp"
        echo ""
        echo "You do not have the necessary permissions to shred the above items in $shredvictim. Continue anyway? (y/N)"
        read badconfirm
        if [[ ! "$badconfirm" == "y" && ! "$badconfirm" == "Y" ]]; then
            shredtemps
            echo ""
            echo "Shred aborted. No changes have been made."
            exit 4
        fi
        echo ""
    fi
fi
if [[ -d "$shredvictim" ]]; then
    echo "Scanning for unremovable files in $shredvictim..."
    if find "$shredvictim" -type d '!' -writable -print -quit 2>/dev/null | grep -q .; then
        anylittlebad=1
        echo "-----------------------------"
        find "$shredvictim" -type d '!' -writable 2>/dev/null
        echo "-----------------------------"
    fi
fi
echo ""
echo "-f,    change permissions to allow writing if necessary"
echo "-n,    overwrite N times instead of the default (3)"
echo "-s,    shred this many bytes (suffixes like K, M, G accepted)"
echo "-u,    deallocate and remove file after overwriting"
echo "-v,    show progress"
echo "-x,    do not round file sizes up to the next full block;"
echo "-z,    add a final overwrite with zeros to hide shredding"
echo "-p,    power off the system after shredding completes (using -l is highly reccomended when using this in case of errors)"
echo "-l,    logs the shred operation to a file. Default location is $HOME/.rshred/logs/"
if [[ $anylittlebad == 1 ]]; then
    echo ""
    echo "WARNING! You do NOT have write permissions in the directories listed above! -u will not work in these directories!"
fi
# Verify that the user entered valid flags. Repeat the prompt until they do.
finalconfirm=0
while [[ "$finalconfirm" != YES ]]; do
    echo "Select the flags you would like to use. Only use one space between -n and its respective value. Same for -s."
    goodchar=0
    while [[ $goodchar == 0 ]]; do
        read flags
        if echo "$flags" | grep -q '[^ fnsuvxzplKMGT0-9\-]'; then
           echo "error: Invalid flags. Please try again."
        else
            goodchar=1
        fi
    done
# We grep the user's input to extract which flags the user has specified, and add them to a variable for later.
    flaggroup=()
    if echo "$flags" | grep -q "f"; then
        flaggroup+=("-f")
    fi
    if echo "$flags" | grep -q "u"; then
        flaggroup+=("-u")
    fi
    if echo "$flags" | grep -q "v"; then
        flaggroup+=("-v")
    fi
    if echo "$flags" | grep -q "x"; then
        flaggroup+=("-x")
    fi
    if echo "$flags" | grep -q "z"; then
        flaggroup+=("-z")
    fi
    if echo "$flags" | grep -q "p"; then
        powerdown=1
    else
        powerdown=0
    fi
    if echo "$flags" | grep -q "l"; then
        logsyes=1
    else
        logsyes=0
    fi
    if echo "$flags" | grep -q "n"; then
        flaggroup+=($(echo "$flags" | grep -o '\-n [0-9]*'))
    fi
    if echo "$flags" | grep -q "s"; then
        flaggroup+=($(echo "$flags" | grep -Eo '\-s [0-9]*[A-Z]?'))
    fi
    if [[ "$exclprompt" == ON && -d "$shredvictim" ]]; then
            promptdirs=()
        echo ""
        echo "Please enter the full paths any directories you would like to exclude from the shredding process. Press ENTER after each path."
        echo "Once you're done, just leave the field blank and hit ENTER. If you have exclusion of directories from config file enable, the ones you enter here will be added on."
        while IFS= read -r item; do
            if [[ -z "$item" ]]; then
                break
            fi
            if [[ ! -d "$item" ]]; then
                echo "error: $item is not a valid directory path."
                continue
            fi
            promptdirs+=("$(realpath "$item")")
        done
        if [[ ${#promptdirs[@]} != 0 ]]; then
            excludedirs+=("${promptdirs[@]}")
        fi
    fi
    echo "-----------------------------------"
    if [[ -d "$shredvictim" ]]; then
        echo "WARNING!! You are about to run shred on $shredvictim with the flags ${flaggroup[@]}! This will RECURSIVELY DESTROY all files within ${shredvictim}!"
        echo "This action is irreverisible! Type \"YES\" and press enter to procceed. You may halt the shredding process at any point with Ctrl+C, but any data already shredded will be permanently lost."
    else
        echo "WARNING!! You are about to run shred on $shredvictim with the flags ${flaggroup[@]}! This will irreversibly destroy the content of ${shredvictim}!"
        echo "Type \"YES\" and press enter to proceed. You may halt the shredding process at any point with Ctrl+C, but any data already shredded will be permanently lost."
    fi
    read finalconfirm
    if [[ ! "$finalconfirm" == YES ]]; then
        echo ""
        echo "Shred aborted. No changes were made."
        echo ""
    fi
    if [[ $logsyes == 1 ]]; then
        mkdir -p "$logpath" > /dev/null 2>&1
        while [[ ( ! -w "$logpath" || ! -x "$logpath" ) && ( "$newlogdirquestion" != "n" && "$newlogdirquestion" != "N" ) ]]; do
            echo "error: Directory at $logpath cannot be created and/or written to. Specify different path? (Y/n)"
            read newlogdirquestion
            if [[ ! "$newlogdirquestion" == "n" && ! "$newlogdirquestion" == "N" ]]; then
                echo "Enter new path."
                read logpath
            else
                echo ""
                echo "Logging will be disabled."
                logsyes=0
                break
            fi
            mkdir -p "$logpath" > /dev/null 2>&1
        done
        logpath="$(realpath "$logpath")""/"
    fi
done
shredstarted=1
if [[ $tempexist == 1 ]]; then
    oldtempexist=1
    oldtemp="$crnttemp"
    crnttemp=$(mktemp -p "$tmppath")
elif [[ "$notemp" == OFF ]]; then
    tempexist=1
    oldtempexist=0
    crnttemp=$(mktemp -p "$tmppath")
else
    crnttemp=/dev/null
fi
if [[ -d "$shredvictim" ]]; then
    echo "Recursively shredding ${shredvictim}..."
else
    echo "Shredding ${shredvictim}..."
fi
# The destruction has begun!
if [[ $logsyes == 1 ]]; then
    logpath="$(realpath "$logpath")"
    logpath+="/rshred log $(date +'%Y-%m-%d %H-%M-%S')"
else
    logpath="/dev/null"
fi
errcount=0
if [[ $yesexclude == ON && ${#excludedirs[@]} != 0 ]]; then
    exdirs=()
    for blkdir in "${excludedirs[@]}"; do
        sanitized="${blkdir//\\/\\\\}"
        sanitized="${sanitized//\*/\\\*}"
        sanitized="${sanitized//\?/\\\?}"
        sanitized="${sanitized//\[/\\\[}"
        sanitized="${sanitized//\]/\\\]}"
        exdirs+=(-wholename "$sanitized" -o)
    done
    unset exdirs[${#exdirs[@]}-1]
fi
if [[ $logsyes == 1 || "$notemp" == OFF ]]; then
    if echo "$flags" | grep -q "v"; then
        if [[ "$yesexclude" == ON && ${#exdirs[@]} != 0 ]]; then
            find "$shredvictim" -type d \( "${exdirs[@]}" \) -prune -o -type f -print0 | xargs -0 shred ${flaggroup[@]} 2>&1 | tee -a "$logpath" "$crnttemp"
        else
            find "$shredvictim" -type f -print0 2>/dev/null | xargs -0 shred ${flaggroup[@]} 2>&1 | tee -a "$logpath" "$crnttemp"
        fi
    else
        if [[ "$yesexclude" == ON && ${#exdirs[@]} != 0 ]]; then
            find "$shredvictim" -type d \( "${exdirs[@]}" \) -prune -o -type f -print0 2>/dev/null | xargs -0 shred ${flaggroup[@]} -v | tee -a "$logpath" "$crnttemp" > /dev/null 2>&1
        else
            find "$shredvictim" -type f -print0 2>/dev/null | xargs -0 shred ${flaggroup[@]} -v | tee -a "$logpath" "$crnttemp" > /dev/null 2>&1
        fi
    fi
else
    if [[ "$yesexclude" == ON && ${#exdirs[@]} != 0 ]]; then
        find "$shredvictim" -type d \( "${exdirs[@]}" \) -prune -o -type f -print0 2>/dev/null | xargs -0 shred ${flaggroup[@]}
    else
        find "$shredvictim" -type f -print0 2>/dev/null | xargs -0 shred ${flaggroup[@]}
    fi
fi
if [[ "$rmvdir" == "ON" ]]; then
    if echo "${flaggroup[@]}" | grep -q "u"; then
        echo "Removing empty directories..." | tee -a "$logpath"
        readarray -d '' filesremaining < <(find "$shredvictim" -type f -print0)
        declare -A unique
        if [[ ${#filesremaining[@]} != 0 ]]; then
            for file in "${filesremaining[@]}"; do
                crntfile="$file"
                while true; do
                    parent="${crntfile%/*}"
                    if [[ -z "$parent" ]]; then
                        parent="/"
                    fi
                    unique["$parent"]=1
                    if [[ "$parent" == "/" || "$parent" == "$shredvictim" ]]; then
                        break
                    fi
                    crntfile="$parent"
                done
            done
        fi
        if [[ "$yesexclude" == ON && ${#exdirs[@]} != 0 ]]; then
            for dir in "${excludedirs[@]}"; do
                unique["$dir"]=1
                crntdir="$dir"
                while true; do
                    parent="${crntdir%/*}"
                    if [[ -z "$parent" ]]; then
                        parent="/"
                    fi
                    unique["$parent"]=1
                    if [[ "$parent" == "/" || "$parent" == "$shredvictim" ]]; then
                        break
                    fi
                    crntdir="$parent"
                done
            done
        fi
        if [[ ${#unique[@]} != 0 ]]; then
            while IFS= read -r -d '' dir; do
                if [[ -z "${unique[$dir]}" ]]; then
                    printf '%s\0' "$dir"
                fi
            done < <(find "$shredvictim" -depth -type d -print0 2>/dev/null) | xargs -0 rmdir 2>&1 | tee -a "$logpath"
        else
            rm -r "$shredvictim" | tee -a "$logpath"
        fi
    fi
fi
echo ${!unique[@]}
if [[ $tempexist == 1 ]]; then
    echo ""
    echo "Checking for errors..."
    if grep -q "failed to open for writing" "$crnttemp"; then
        errcount=$(grep -c "failed to open for writing" "$crnttemp")
        shredtemps
        echo "" | tee -a "$logpath"
        if [[ $logsyes == 1 ]]; then
            echo "Shredding of $shredvictim completed, but encountered $errcount errors. Please check $logpath for more info." | tee -a "$logpath"
        else
            echo "Shredding of $shredvictim completed, but encountered $errcount errors."
        fi
        if [[ $powerdown == 1 ]]; then
            echo "Shutting down host..."
            poweroff
        fi
    else
        shredtemps
        echo "" | tee -a "$logpath"
        echo "Shredding of $shredvictim completed. No errors found." | tee -a "$logpath"
        if [[ $powerdown == 1 ]]; then
            echo "Shutting down host..." | tee -a "$logpath"
            poweroff
        fi
    fi
elif [[ $logsyes == 1 ]]; then
    echo ""
    echo "Checking for errors..."
    if grep -q "failed to open for writing" "$logpath"; then
        errcount=$(grep -c "failed to open for writing" "$logpath")
        shredtemps
        echo ""
        echo "Shredding of $shredvictim completed, but encountered $errcount errors. Please check $logpath for more info." | tee -a "$logpath"
        if [[ $powerdown == 1 ]]; then
            echo "Shutting down host..." | tee -a "$logpath"
            poweroff
        fi
    else
        shredtemps
        echo ""
        echo "Shredding of $shredvictim completed. No errors found." | tee -a "$logpath"
        if [[ $powerdown == 1 ]]; then
            echo "Shutting down host..." | tee -a "$logpath"
            poweroff
        fi
    fi
else
    echo ""
    echo "Shredding of $shredvictim completed."
fi
echo "${exdirs[@]}"
